version: '2'

networks: 
    example.com: 

services:

    orderer:
        image: hyperledger/fabric-orderer:1.4.3 
        container_name: orderer
        working_dir: /var/hyperledger/orderer 
        environment:
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file 
            - ORDERER_GENERAL_GENESISPROFILE=TwoOrgsOrdererGenesis 
            - ORDERER_GENERAL_SYSTEMCHANNEL=syschannel 
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/data/genesis.block 
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP 
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp 
            - ORDERER_GENERAL_TLS_ENABLED=true 
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key 
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt 
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
            - ORDERER_KAFKA_VERBOSE=true 
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key 
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt 
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
        volumes:
            - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp 
            - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls 
            - ./state/orderer:/var/hyperledger/production/orderer
            - ./channel-artifacts/:/var/hyperledger/orderer/data/
        ports:
            - 7050:7050
        networks:
            - example.com 

    peer0.org1.example.com: 
        image: hyperledger/fabric-peer:1.4.3 
        container_name: peer0.org1.example.com 
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer 
        environment:
            - CORE_VM_ENDPOINT=unix:///var/run/docker.sock 
            - CORE_PEER_ADDRESSAUTODETECT=true 
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bridge 
            - CORE_VM_DOCKER_ATTACHOUT=true 
            - CORE_PEER_ID=peer0.org1.example.com 
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:8051 
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_ENDPOINT=peer0.org1.example.com:7051 
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 
            - CORE_PEER_LOCALMSPID=Org1MSP 
            - CORE_PEER_ENDORSER_ENABLED=true 
            - CORE_PEER_GOSSIP_USELEADERELECTION=true 
            - CORE_PEER_TLS_ENABLED=true 
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt 
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key 
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt 
        volumes:
            - /var/run/:/host/var/run/ 
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp 
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls 
            - ./state/peer0.org1.example.com:/var/hyperledger/production 
            - ./crypto-config/ordererOrganizations/example.com:/etc/hyperledger/orderers 
        ports:
            - 7051:7051
        depends_on:
            - orderer 
        networks:
            - example.com 
        
    
    peer1.org1.example.com: 
        image: hyperledger/fabric-peer:1.4.3 
        container_name: peer1.org1.example.com 
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer 
        environment:
            - CORE_VM_ENDPOINT=unix:///var/run/docker.sock 
            - CORE_PEER_ADDRESSAUTODETECT=true 
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bridge 
            - CORE_VM_DOCKER_ATTACHOUT=true 
            - CORE_PEER_ID=peer1.org1.example.com 
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051 
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8051
            - CORE_PEER_GOSSIP_ENDPOINT=peer1.org1.example.com:8051 
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 
            - CORE_PEER_LOCALMSPID=Org1MSP 
            - CORE_PEER_ENDORSER_ENABLED=true 
            - CORE_PEER_GOSSIP_USELEADERELECTION=true 
            - CORE_PEER_TLS_ENABLED=true 
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt 
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key 
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt 
        volumes:
            - /var/run/:/host/var/run/ 
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp 
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls 
            - ./state/peer1.org1.example.com:/var/hyperledger/production 
            - ./crypto-config/ordererOrganizations/example.com:/etc/hyperledger/orderers 
        ports:
            - 8051:7051
        depends_on:
            - orderer 
        networks:
            - example.com 





    peer0.org2.example.com: 
        image: hyperledger/fabric-peer:1.4.3 
        container_name: peer0.org2.example.com 
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer 
        environment:
            - CORE_VM_ENDPOINT=unix:///var/run/docker.sock 
            - CORE_PEER_ADDRESSAUTODETECT=true 
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bridge 
            - CORE_VM_DOCKER_ATTACHOUT=true 
            - CORE_PEER_ID=peer0.org2.example.com 
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:10051 
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:9051
            - CORE_PEER_GOSSIP_ENDPOINT=peer0.org2.example.com:9051 
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 
            - CORE_PEER_LOCALMSPID=Org2MSP 
            - CORE_PEER_ENDORSER_ENABLED=true 
            - CORE_PEER_GOSSIP_USELEADERELECTION=true 
            - CORE_PEER_TLS_ENABLED=true 
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt 
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key 
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt 
        volumes:
            - /var/run/:/host/var/run/ 
            - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp 
            - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls 
            - ./state/peer0.org2.example.com:/var/hyperledger/production 
            - ./crypto-config/ordererOrganizations/example.com:/etc/hyperledger/orderers 
        ports:
            - 9051:7051
        depends_on:
            - orderer 
        networks:
            - example.com 
        
    
    peer1.org2.example.com: 
        image: hyperledger/fabric-peer:1.4.3 
        container_name: peer1.org2.example.com 
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer 
        environment:
            - CORE_VM_ENDPOINT=unix:///var/run/docker.sock 
            - CORE_PEER_ADDRESSAUTODETECT=true 
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bridge 
            - CORE_VM_DOCKER_ATTACHOUT=true 
            - CORE_PEER_ID=peer1.org2.example.com 
            - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051 
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:10051
            - CORE_PEER_GOSSIP_ENDPOINT=peer1.org2.example.com:10051 
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052 
            - CORE_PEER_LOCALMSPID=Org2MSP 
            - CORE_PEER_ENDORSER_ENABLED=true 
            - CORE_PEER_GOSSIP_USELEADERELECTION=true 
            - CORE_PEER_TLS_ENABLED=true 
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt 
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key 
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt 
        volumes:
            - /var/run/:/host/var/run/ 
            - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp 
            - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls 
            - ./state/peer1.org2.example.com:/var/hyperledger/production 
            - ./crypto-config/ordererOrganizations/example.com:/etc/hyperledger/orderers 
        ports:
            - 10051:7051
        depends_on:
            - orderer 
        networks:
            - example.com 